### PR TITLE
Default view

### PR DESCRIPTION
**Pull request by dsobirk**
Allow the user to select which view to show media in. Default view is Confluence mediainfo.

### CODE REVIEW

**Comment by marcelveldt** [comment]
I think this is a great idea to append to the addon but I'd like to suggest a small modification.
Better to be able to set the view for each content type:

albums
artists
playlists
songs

Otherwise you will end up in a default view for all content types.

Don't know if you have interest in making it that way or you want me to do so ?

Thanks anyway for your contribution!

**Comment by dsobirk** [comment]
Makes sense. I'll look into it.

**Comment by dsobirk** [comment]
Something like this?

**Comment by marcelveldt** [comment]
Yes, that's what I mean. And I think you forgot to check in the settings.xml file ;-)

**Comment by dsobirk** [comment]
Hmm, new settings.xml should be part of 2861f6c1e3bb6e94af26be9da745af8902d086d9
Would have been nicer to squash the commits together, but I'm unfortunately not familiar enough with git to make it happen.

**Comment by dsobirk** [comment]
Are you ok with this, or would you like some additional changes?

**Comment by marcelveldt** [comment]
Great stuff, thanks for your time adding it !

**Pull request merged**
